timezone: "Asia/Shanghai"

location:
  name: "大鹏半岛·杨梅坑"
  lat: 22.54691
  lon: 114.56853
  metar: "ZGSZ"   # 深圳宝安

scoring:
  low_cloud: [0, 40, 70]          # 低云%
  mid_high_cloud: [20, 60, 85]    # 中/高云%（取最大）
  cloud_base_m: [500, 1000]       # 云底高度 m 阈值
  visibility_km: [8, 15]
  wind_ms: [0, 2, 5, 8]           # 四个点（见 calc_score）
  dewpoint_diff: [1, 3]           # 露点差 ℃
  precip_mm: [0.1, 1]             # 降雨 mm

cloudwall:
  sunrise_azimuth: 90             # 低云墙采样方向（日出方向，大致东方），日落可再配一个字段
  sample_km: [20, 50, 80, 120]
  cb_lapse_m_per_degC: 125        # 云底估算常数(m/°C)

paths:
  log_scores: "logs/scores_%Y-%m.csv"
  log_cloud:  "logs/cloud_%Y-%m.csv"

meteoblue:
  api_key: ""  # 建议用 GitHub Secret: MB_API_KEY
