name: Deploy Frontend to Pages
on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy_pages.yml'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: frontend
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2
