name: Generate Forecast JSON

# ❶ 触发条件
on:
  workflow_dispatch:             # 手动点 Run workflow
    inputs:
      lat:
        description: "Latitude"
        required: false
        default: "22.54691"
      lon:
        description: "Longitude"
        required: false
        default: "114.56853"
      date:
        description: "Date (YYYY-MM-DD), empty=today/tomorrow auto"
        required: false
        default: ""
  schedule:                      # 每天 05:30 北京时间 = 21:30 UTC 前一天
    - cron: "30 21 * * *"

  # 如果你还想在改后端脚本时自动跑，就加 paths 过滤：
  push:
    paths:
      - "backend/**"
      - "config.yaml"
      - ".github/workflows/run_forecast.yml"

# ❷ 必要写权限（要把生成的 JSON push 回仓库）
permissions:
  contents: write

concurrency:
  group: forecast-${{ github.ref }}
  cancel-in-progress: false

jobs:
  forecast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install -r requirements.txt

      - name: Run generator
        env:
          MB_API_KEY: ${{ secrets.MB_API_KEY }}   # 有就用，没有也不报错
        run: |
          mkdir -p data/requests
          python backend/generate_forecast.py \
            --lat "${{ github.event.inputs.lat || '22.54691' }}" \
            --lon "${{ github.event.inputs.lon || '114.56853' }}" \
            --date "${{ github.event.inputs.date || '' }}"

      - name: Commit & push JSON
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/requests/*.json || echo "no json"
          git commit -m "Update forecast $(date -u '+%F %T UTC')" || exit 0
          git push
